document.addEventListener("DOMContentLoaded", function() {
  const subtitles = [
    "idk what to put here",
    "Zammy is pretty cool",
    "did u know we have a discord server?",
    "Skipipipi",
    "Blahaj go spinny",
    "Deku from MHA is zesty",
    "Name=Yug is pro :)",
    "the owner  has kids in basement",
    "@NikoPikoPoo is not a pro piko poo",
    "Gen alpha sucks",
    "Rena: Subtitile I spelt this shi hella wrong anyways",
    "these subtitles are so random",
    "im running out of ideas",
    "vscode suggested these xd",
    "these are so random",
    "nice face",
    "smile your camera is being recorded",
    "Valorant is ying yang game and Fortnite is a good mæn’s game",
    "Russians are CS PROS ",
    "I put the 'pro' in procrastination",
    "404 brain not found",
    "My brain has too many tabs open",
    "I speak fluent sarcasm",
    "Running on caffeine and chaos",
    "I’m not lazy, I’m on energy-saving mode",
    "I’m silently correcting your grammar",
    "I’m not arguing, I’m just explaining why I’m right",
    "I’m on a seafood diet. I see food and I eat it",
    "I’m not weird, I’m limited edition",
    "I’m not short, I’m fun-sized",
    "I’m not clumsy, I’m just on a gravity-friendly diet",
    "I’m not late, I’m just early for tomorrow",
    "I’m not a complete idiot, some parts are missing",
    "I’m not crazy, my reality is just different than yours",
    "I’m not bossy, I just have better ideas",
    "I’m not lazy, I’m just highly motivated to do nothing",
    "I’m not shy, I’m just holding back my awesomeness",
    "I’m not a morning person, I’m a coffee person",
    "I’m not a control freak, I just know what’s best",
    "I’m not a procrastinator, I’m just extremely productive at unimportant things",
    "I’m not a genius, I’m just a work in progress",
    "I’m not a quitter, I’m just re-evaluating my priorities",
    "I’m not a perfectionist, I’m just really good at being right",
    "I’m not a people person, I’m a selective socializer",
    "I’m not a morning person, I’m a night owl",
    "I’m not a robot, I’m just programmed to be awesome",
    "I’m not a mind reader, but I can read your face",
    "I’m not a magician, but I can make your boredom disappear",
    "I’m not a chef, but I can make a mean bowl of cereal",
    "I’m not a doctor, but I can fix your boredom",
    "I’m not a superhero, but I can save your day",
    "I’m not a comedian, but I can make you laugh",
    "I’m not a singer, but I can make you smile",
    "I’m not a dancer, but I can make you groove",
    "I’m not a writer, but I can tell a good story",
    "I’m not a poet, but I can rhyme anytime",
    "I’m not a painter, but I can color your world",
    "I’m not a photographer, but I can capture your heart",
    "I’m not a scientist, but I can experiment with fun",
    "I’m not a teacher, but I can educate you on silliness",
    "I’m not a lawyer, but I can argue for fun",
    "I’m not a detective, but I can solve your boredom",
    "I’m not a pilot, but I can take you on a fun journey",
    "I’m not a gardener, but I can plant a smile on your face",
    "I’m not a builder, but I can construct a good time",
    "I’m not a sailor, but I can navigate you to fun",
    "I’m not a chef, but I can cook up some laughs",
    "I’m not a musician, but I can play a good joke",
    "I’m not a therapist, but I can listen to your silliness"
    
  ];
  
  // Select a random subtitle
  const randomIndex = Math.floor(Math.random() * subtitles.length);
  const subtitleElement = document.getElementById("subtitle");
  
  // Set the initial subtitle to a random one
  subtitleElement.textContent = subtitles[randomIndex];
});
